### ISSUE TITLE
Documentation and tests needed

### ISSUE THREAD

**Issue by pwaller** [rootpy/rootpy#312]
Please edit the following text to add issues/pull requests which involve documenting or adding tests for features which have been recently added.
- [ ] #286 : Regular expression searching within files/directories
- [ ] #307 : rootpy.ROOT
- [ ] #308 : TList manipulation
- [ ] #314 : Document code breakage as a result of types module rename
- [ ] #315 : Automatic binning
- [ ] #280 : Document BinProxy and add an example
